# Generated by Django 5.0.4 on 2024-06-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildBMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RSID', models.CharField(max_length=100)),
                ('CHR', models.IntegerField(null=True)),
                ('BP', models.IntegerField(null=True)),
                ('BETA', models.FloatField(null=True)),
                ('SE', models.FloatField(null=True)),
                ('P', models.FloatField(null=True)),
                ('AGE', models.FloatField(null=True)),
                ('cBP', models.IntegerField(null=True)),
            ],
        ),
    ]
